SP_Configuration:
  - { ip_address: 10.1.1.1, netmask: 255.255.255.0, gateway_ip_address: 10.1.1.254, node: cluster1-01}
  - { ip_address: 10.1.1.2, netmask: 255.255.255.0, gateway_ip_address: 10.1.1.253, node: cluster1-02}
